// <auto-generated />
using System;
using Events.WebApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Events.WebApi.Migrations
{
    [DbContext(typeof(EventsContext))]
    [Migration("20240904153607_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Events.Domain_Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPeopleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Minsk 123",
                            Category = 0,
                            DateTime = new DateTime(2024, 9, 4, 18, 36, 5, 688, DateTimeKind.Utc).AddTicks(5794),
                            Description = "Top level concert",
                            ImagePath = "concert.png",
                            MaxPeopleCount = 4,
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mos cow, 12",
                            Category = 1,
                            DateTime = new DateTime(2024, 9, 4, 18, 36, 5, 688, DateTimeKind.Utc).AddTicks(5823),
                            Description = "description ...",
                            ImagePath = "meeting.png",
                            MaxPeopleCount = 10,
                            Name = "Allowed meeting"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Paris, Sena",
                            Category = 2,
                            DateTime = new DateTime(2024, 9, 4, 18, 36, 5, 688, DateTimeKind.Utc).AddTicks(5827),
                            Description = "Frogs?",
                            ImagePath = "paris.jpg",
                            MaxPeopleCount = 9,
                            Name = "Fair with tail"
                        });
                });

            modelBuilder.Entity("Events.Domain_Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Participation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            RegistrationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            RegistrationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EventId = 2,
                            RegistrationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Events.Domain_Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1, 1, 1),
                            Email = "lol@gmail.com",
                            Name = "Pasha",
                            Password = "Pass123",
                            Surname = "First"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1, 1, 1),
                            Email = "crol@mail.ru",
                            Name = "Petia",
                            Password = "Vass123",
                            Surname = "Second"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1, 1, 1),
                            Email = "esc@gmama.help",
                            Name = "Vova",
                            Password = "Kiss123",
                            Surname = "Third"
                        });
                });

            modelBuilder.Entity("Events.WebApi.Authentication.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Value");
                });

            modelBuilder.Entity("Events.Domain_Entities.Participation", b =>
                {
                    b.HasOne("Events.Domain_Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Events.Domain_Entities.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Events.Domain_Entities.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Events.Domain_Entities.User", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
