// <auto-generated />
using System;
using Events.WebApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Events.WebApi.Migrations
{
    [DbContext(typeof(EventsContext))]
    [Migration("20240905081602_AddExpiresToRefreshTokenMigration")]
    partial class AddExpiresToRefreshTokenMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Events.Domain_Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPeopleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Minsk 123",
                            Category = 0,
                            DateTime = new DateTime(2024, 9, 5, 11, 16, 1, 578, DateTimeKind.Utc).AddTicks(2144),
                            Description = "Top level concert",
                            ImagePath = "concert.png",
                            MaxPeopleCount = 4,
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mos cow, 12",
                            Category = 1,
                            DateTime = new DateTime(2024, 9, 5, 11, 16, 1, 578, DateTimeKind.Utc).AddTicks(2167),
                            Description = "description ...",
                            ImagePath = "meeting.png",
                            MaxPeopleCount = 10,
                            Name = "Allowed meeting"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Paris, Sena",
                            Category = 2,
                            DateTime = new DateTime(2024, 9, 5, 11, 16, 1, 578, DateTimeKind.Utc).AddTicks(2169),
                            Description = "Frogs?",
                            ImagePath = "paris.jpg",
                            MaxPeopleCount = 9,
                            Name = "Fair with tail"
                        });
                });

            modelBuilder.Entity("Events.Domain_Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Participation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            RegistrationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            RegistrationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EventId = 2,
                            RegistrationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Events.Domain_Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e5d0b08-9eab-4688-9686-9a7179dacc2f",
                            DateOfBirth = new DateOnly(1, 1, 1),
                            Email = "lol@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "Pass123",
                            PhoneNumberConfirmed = false,
                            Surname = "First",
                            TwoFactorEnabled = false,
                            UserName = "Pasha"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c585c906-5ce8-4897-b0ec-e5311a603c08",
                            DateOfBirth = new DateOnly(1, 1, 1),
                            Email = "crol@mail.ru",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "Vass123",
                            PhoneNumberConfirmed = false,
                            Surname = "Second",
                            TwoFactorEnabled = false,
                            UserName = "Petia"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb5d0b63-4d55-465e-89cc-622944fe5bc8",
                            DateOfBirth = new DateOnly(1, 1, 1),
                            Email = "esc@gmama.help",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Password = "Kiss123",
                            PhoneNumberConfirmed = false,
                            Surname = "Third",
                            TwoFactorEnabled = false,
                            UserName = "Vova"
                        });
                });

            modelBuilder.Entity("Events.WebApi.Authentication.RefreshToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserRefreshToken");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Events.Domain_Entities.Participation", b =>
                {
                    b.HasOne("Events.Domain_Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Events.Domain_Entities.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Events.WebApi.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Events.Domain_Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Events.WebApi.Authentication.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Events.Domain_Entities.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Events.Domain_Entities.User", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
