
GET {{HostAddress}}/api/Users

###

GET {{HostAddress}}/api/Users/2

###

POST {{HostAddress}}/api/Users
Content-Type: application/json

{
    "name": "Katya",
    "email": "katya123@gmail.ru",
    "surname": "Ivanova",
    "password": "qwerty123",
    "dateOfBirth": "2004-09-01"
}

###

PUT {{HostAddress}}/api/Users/2
Content-Type: application/json

{
    "id": 2,
    "name": "string"
}

###

DELETE {{HostAddress}}/api/Users/2
