

GET {{HostAddress}}/api/TodoItems

###

POST {{HostAddress}}/api/TodoItems
Content-Type: application/json

{
    "id": 2,
    "name": "HTTP test2",
    "isComplete": true
}

###

PUT {{HostAddress}}/api/TodoItems/3
Content-Type: application/json

{
    "id": 3,
    "name": "LOL",
    "isComplete": false
}

